VMS = AsteroidsGame.vm Fraction.vm Main.vm MathExt.vm ScreenExt.vm Ship.vm

JACKCOMPILER=C:\Users\bbecke01\Documents\Repos\coursera-nand2tetris\nand2tetris\tools\JackCompiler.bat
%.vm: %.jack
	$(JACKCOMPILER) $<

all: $(VMS)
